// Comprehensive VC history data structured for subway-style visualization
// Based on "The Power Law" by Sebastian Mallaby

export interface SubwayNode {
  id: string
  date: string // YYYY-MM-DD
  title: string
  description: string
  type: "firm_founding" | "investment" | "ipo" | "acquisition" | "person_move" | "milestone"
  x?: number // Will be calculated based on date
  y?: number // Will be calculated based on line
  connections: string[] // IDs of connected nodes
  lineId: string
  importance: 1 | 2 | 3 // 1=minor, 2=major, 3=legendary
  link?: string // Optional link for more details
}

export interface SubwayLine {
  id: string
  name: string
  color: string
  startDate: string
  endDate?: string // undefined means still active
  parentLineId?: string // for lines that spawn from others
  nodes: string[] // node IDs in chronological order
}

export const subwayLines: SubwayLine[] = [
  {
    id: "ardc_line",
    name: "ARDC/East Coast",
    color: "#1e40af",
    startDate: "1946-06-06",
    endDate: "1971-12-31", // Match ARDC founding
    nodes: [],
  },
  {
    id: "fairchild_line",
    name: "Fairchild Ecosystem",
    color: "#dc2626",
    startDate: "1957-10-01",
    endDate: "2016-09-19", // Match Fairchild founding
    nodes: [],
  },
  {
    id: "venrock_line",
    name: "Venrock",
    color: "#0ea5e9",
    startDate: "1969-01-01",
    nodes: [],
  },
  {
    id: "intel_line",
    name: "Intel Line",
    color: "#0891b2",
    startDate: "1968-07-18", // Match Intel founding
    parentLineId: "fairchild_line",
    nodes: [],
  },
  {
    id: "kp_line",
    name: "Kleiner Perkins",
    color: "#16a34a",
    startDate: "1972-01-01", // Match KP founding
    parentLineId: "fairchild_line",
    nodes: [],
  },
  {
    id: "sequoia_line",
    name: "Sequoia Capital",
    color: "#ea580c",
    startDate: "1972-11-01", // Match Sequoia founding - FIXED
    parentLineId: "fairchild_line",
    nodes: [],
  },
  {
    id: "softbank_line",
    name: "SoftBank / Vision Fund",
    color: "#f43f5e",
    startDate: "1981-09-03",
    nodes: [],
  },
  {
    id: "accel_line",
    name: "Accel Partners",
    color: "#7c3aed",
    startDate: "1983-01-01", // Match Accel founding
    nodes: [],
  },
  {
    id: "benchmark_line",
    name: "Benchmark Capital",
    color: "#be185d",
    startDate: "1995-01-01", // Match Benchmark founding
    nodes: [],
  },
  {
    id: "yc_line",
    name: "Y Combinator",
    color: "#f59e0b",
    startDate: "2005-03-01", // Match YC founding
    nodes: [],
  },
  {
    id: "sequoia_china_line",
    name: "Sequoia China",
    color: "#d97706",
    startDate: "2005-09-01", // Match Sequoia China founding
    parentLineId: "sequoia_line",
    nodes: [],
  },
  {
    id: "founders_fund_line",
    name: "Founders Fund",
    color: "#db2777",
    startDate: "2005-07-01", // Match Founders Fund founding
    parentLineId: "sequoia_line",
    nodes: [],
  },
  {
    id: "a16z_line",
    name: "Andreessen Horowitz",
    color: "#8b5cf6",
    startDate: "2009-07-01", // Match a16z founding
    nodes: [],
    parentLineId: "kp_line",
  },
]

export const subwayNodes: SubwayNode[] = [
  // ARDC Era (1946-1970s)
  {
    id: "ardc_founding",
    date: "1946-06-06",
    title: "🚀 ARDC Founded",
    description:
      "Georges Doriot founds American Research and Development Corporation in Boston, the first modern VC firm",
    type: "firm_founding",
    connections: ["doriot_dec_investment"],
    lineId: "ardc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/American_Research_and_Development_Corporation",
  },
  {
    id: "doriot_dec_investment",
    date: "1957-03-01",
    title: "💰 ARDC → DEC Investment",
    description: "ARDC invests $70,000 for 70% of Digital Equipment Corporation",
    type: "investment",
    connections: ["ardc_founding", "dec_ipo"],
    lineId: "ardc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Digital_Equipment_Corporation",
  },
  {
    id: "dec_ipo",
    date: "1966-08-18",
    title: "📈 DEC IPO",
    description: "DEC goes public, ARDC's $70k becomes $355M - first demonstration of the power law",
    type: "ipo",
    connections: ["doriot_dec_investment"],
    lineId: "ardc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Digital_Equipment_Corporation",
  },

  // Fairchild Era - The Genesis (1957-1970s)
  {
    id: "shockley_founding",
    date: "1956-02-01",
    title: "🚀 Shockley Semiconductor Founded",
    description:
      "William Shockley founds Shockley Semiconductor Laboratory, attracting top talent but leading to rebellion",
    type: "firm_founding",
    connections: ["traitorous_eight"],
    lineId: "fairchild_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Shockley_Semiconductor_Laboratory",
  },
  {
    id: "traitorous_eight",
    date: "1957-09-18",
    title: "👔 Traitorous Eight Leave Shockley",
    description: "Gordon Moore, Robert Noyce, Eugene Kleiner and 5 others leave Shockley Semiconductor",
    type: "person_move",
    connections: ["shockley_founding", "fairchild_founding"],
    lineId: "fairchild_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Traitorous_eight",
  },
  {
    id: "fairchild_founding",
    date: "1957-10-01",
    title: "🚀 Fairchild Semiconductor Founded",
    description: "Sherman Fairchild backs the Traitorous Eight with $1.5M",
    type: "firm_founding",
    connections: [
      "traitorous_eight",
      "fairchild_ipo",
      "intel_founding",
      "amd_founding",
      "kp_founding",
      "sequoia_founding",
    ],
    lineId: "fairchild_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Fairchild_Semiconductor",
  },
  {
    id: "fairchild_ipo",
    date: "1961-09-01",
    title: "📈 Fairchild IPO",
    description: "Fairchild goes public, making millionaires of the founders",
    type: "ipo",
    connections: ["fairchild_founding"],
    lineId: "fairchild_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Fairchild_Semiconductor",
  },
  {
    id: "rock_formation",
    date: "1961-01-01",
    title: "👔 Arthur Rock Starts Investing",
    description: "Arthur Rock leaves Hayden Stone to become independent investor, backs Fairchild and Intel",
    type: "person_move",
    connections: ["fairchild_founding", "intel_founding"],
    lineId: "fairchild_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Arthur_Rock",
  },
  {
    id: "national_semi_founding",
    date: "1959-05-27",
    title: "🚀 National Semiconductor Founded",
    description: "Spin-off from Sperry Rand, later employs Don Valentine",
    type: "firm_founding",
    connections: ["valentine_national_semi"],
    lineId: "fairchild_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/National_Semiconductor",
  },
  {
    id: "rock_sds_investment",
    date: "1961-01-01",
    title: "💰 Rock → SDS Investment",
    description: "Arthur Rock and Tommy Davis invest in Scientific Data Systems, which grows rapidly",
    type: "investment",
    connections: ["rock_formation", "sds_acquisition"],
    lineId: "fairchild_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Scientific_Data_Systems",
  },
  {
    id: "sds_acquisition",
    date: "1969-01-01",
    title: "📈 SDS Acquired by Xerox",
    description: "Xerox acquires Scientific Data Systems for $900M, validating Rock's model",
    type: "acquisition",
    connections: ["rock_sds_investment"],
    lineId: "fairchild_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Scientific_Data_Systems",
  },

  // Intel Line - The Semiconductor Revolution
  {
    id: "intel_founding",
    date: "1968-07-18",
    title: "🚀 Intel Founded",
    description: "Robert Noyce and Gordon Moore leave Fairchild to start Intel with Arthur Rock's backing",
    type: "firm_founding",
    connections: ["fairchild_founding", "rock_formation", "intel_ipo", "doerr_joins_intel", "doerr_joins_kp"],
    lineId: "intel_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Intel",
  },
  {
    id: "amd_founding",
    date: "1969-05-01",
    title: "🚀 AMD Founded",
    description: "Jerry Sanders leads exodus from Fairchild to found Advanced Micro Devices",
    type: "firm_founding",
    connections: ["fairchild_founding"],
    lineId: "fairchild_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Advanced_Micro_Devices",
  },
  {
    id: "intel_ipo",
    date: "1971-10-13",
    title: "📈 Intel IPO",
    description: "Intel goes public at $23.50/share, validating the semiconductor revolution",
    type: "ipo",
    connections: ["intel_founding"],
    lineId: "intel_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Intel",
  },
  {
    id: "doerr_joins_intel",
    date: "1974-01-01",
    title: "👔 John Doerr Joins Intel",
    description: "John Doerr joins Intel as an engineer after college",
    type: "person_move",
    connections: ["intel_founding", "doerr_joins_kp"],
    lineId: "intel_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/John_Doerr",
  },

  // Kleiner Perkins Line - The Biotech and Internet Pioneer
  {
    id: "kp_founding",
    date: "1972-01-01",
    title: "🚀 Kleiner Perkins Founded",
    description: "Eugene Kleiner (Fairchild) and Tom Perkins (HP) found Kleiner Perkins",
    type: "firm_founding",
    connections: ["fairchild_founding", "kp_tandem", "kp_genentech", "doerr_joins_kp"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Kleiner_Perkins",
  },
  {
    id: "tandem_founding",
    date: "1974-01-01",
    title: "🚀 Tandem Computers Founded",
    description: "Jimmy Treybig founds Tandem Computers with KP backing",
    type: "firm_founding",
    connections: ["kp_tandem"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Tandem_Computers",
  },
  {
    id: "kp_tandem",
    date: "1974-06-01",
    title: "💰 KP → Tandem Computers",
    description: "Kleiner Perkins invests in Tandem Computers, pioneering fault-tolerant systems",
    type: "investment",
    connections: ["kp_founding", "tandem_founding", "tandem_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Tandem_Computers",
  },
  {
    id: "kp_cetus",
    date: "1974-01-01",
    title: "💰 KP → Cetus",
    description: "Kleiner Perkins invests in Cetus, an early biotech firm",
    type: "investment",
    connections: ["kp_founding", "kp_genentech"],
    lineId: "kp_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Cetus_Corporation",
  },
  {
    id: "kp_genentech",
    date: "1976-04-07",
    title: "💰 KP → Genentech",
    description: "Kleiner Perkins invests in Genentech, pioneering biotech VC",
    type: "investment",
    connections: ["kp_founding", "kp_cetus", "genentech_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Genentech",
  },
  {
    id: "tandem_ipo",
    date: "1977-12-15",
    title: "📈 Tandem IPO",
    description: "Tandem Computers goes public, returning multiples to KP",
    type: "ipo",
    connections: ["kp_tandem"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Tandem_Computers",
  },
  {
    id: "erisa_prudent_man",
    date: "1979-01-01",
    title: "⭐ ERISA Prudent Man Rule Change",
    description: "US Dept of Labor changes ERISA rules, allowing pension funds to invest in VC",
    type: "milestone",
    connections: ["capital_gains_tax_cut", "genentech_ipo", "apple_ipo"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Employee_Retirement_Income_Security_Act_of_1974",
  },
  {
    id: "doerr_joins_kp",
    date: "1980-01-01",
    title: "👔 John Doerr Joins KP",
    description: "John Doerr leaves Intel to join Kleiner Perkins as partner",
    type: "person_move",
    connections: ["doerr_joins_intel", "intel_founding", "kp_founding", "kp_compaq", "kp_amazon", "kp_sequoia_google"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/John_Doerr",
  },
  {
    id: "genentech_ipo",
    date: "1980-10-14",
    title: "📈 Genentech IPO",
    description: "Genentech IPO creates first biotech billionaire (Boyer) and validates biotech investing",
    type: "ipo",
    connections: ["kp_genentech"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Genentech",
  },
  {
    id: "kp_compaq",
    date: "1982-06-01",
    title: "💰 KP → Compaq",
    description: "Kleiner Perkins invests in Compaq, backing PC revolution",
    type: "investment",
    connections: ["doerr_joins_kp", "compaq_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Compaq",
  },
  {
    id: "kp_sun",
    date: "1982-02-01",
    title: "💰 KP → Sun Microsystems",
    description: "Kleiner Perkins invests in Sun Microsystems, pioneering workstations",
    type: "investment",
    connections: ["doerr_joins_kp", "sun_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Sun_Microsystems",
  },
  {
    id: "kp_lotus",
    date: "1982-04-01",
    title: "💰 KP → Lotus",
    description: "Kleiner Perkins invests in Lotus Development, creators of 1-2-3 spreadsheet",
    type: "investment",
    connections: ["doerr_joins_kp", "lotus_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Lotus_Software",
  },
  {
    id: "compaq_ipo",
    date: "1983-12-09",
    title: "📈 Compaq IPO",
    description: "Compaq goes public, becoming fastest startup to $100M revenue",
    type: "ipo",
    connections: ["kp_compaq"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Compaq",
  },
  {
    id: "sun_ipo",
    date: "1986-03-04",
    title: "📈 Sun Microsystems IPO",
    description: "Sun goes public, validating workstation market",
    type: "ipo",
    connections: ["kp_sun"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Sun_Microsystems",
  },
  {
    id: "lotus_ipo",
    date: "1983-10-06",
    title: "📈 Lotus IPO",
    description: "Lotus goes public, dominating spreadsheet software",
    type: "ipo",
    connections: ["kp_lotus"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Lotus_Software",
  },
  {
    id: "kp_aol",
    date: "1994-01-01",
    title: "💰 KP → AOL",
    description: "Kleiner Perkins invests in America Online, betting on consumer internet",
    type: "investment",
    connections: ["doerr_joins_kp", "aol_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/AOL",
  },
  {
    id: "netscape_founding",
    date: "1994-04-04",
    title: "🚀 Netscape Founded",
    description: "Marc Andreessen and Jim Clark found Netscape",
    type: "firm_founding",
    connections: ["kp_founding", "netscape_ipo", "a16z_founding"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Netscape",
  },
  {
  id: "kp_netscape",
  date: "1994-09-01",
  title: "💰 KP → Netscape",
  description: "Kleiner Perkins invests in Netscape, backing the Internet revolution",
  type: "investment",
  connections: ["kp_founding", "netscape_founding", "netscape_ipo"],
  lineId: "kp_line",
  importance: 2,
  link: "https://www.kleinerperkins.com/case-study/netscape/"
},
  {
    id: "netscape_ipo",
    date: "1995-08-09",
    title: "📈 Netscape IPO",
    description: "Netscape IPO launches internet boom, stock doubles on first day",
    type: "ipo",
    connections: ["netscape_founding", "a16z_founding"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Netscape",
  },
  {
    id: "aol_ipo",
    date: "1992-03-19",
    title: "📈 AOL IPO",
    description: "AOL goes public, but KP investment helps scale during internet boom",
    type: "ipo",
    connections: ["kp_aol"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/AOL",
  },
  {
    id: "kp_amazon",
    date: "1996-06-01",
    title: "💰 KP → Amazon",
    description: "John Doerr leads Kleiner Perkins' $8M investment in Amazon",
    type: "investment",
    connections: ["doerr_joins_kp", "amazon_ipo"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Amazon_(company)",
  },
  {
    id: "kp_at_home",
    date: "1996-01-01",
    title: "💰 KP → @Home",
    description: "Kleiner Perkins invests in @Home Network for broadband internet",
    type: "investment",
    connections: ["doerr_joins_kp", "at_home_ipo"],
    lineId: "kp_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Excite_(web_portal)#@Home_Network",
  },
  {
    id: "amazon_ipo",
    date: "1997-05-15",
    title: "📈 Amazon IPO",
    description: "Amazon IPO at $18/share, Kleiner Perkins stake worth billions today",
    type: "ipo",
    connections: ["kp_amazon"],
    lineId: "kp_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Amazon_(company)",
  },
  {
    id: "at_home_ipo",
    date: "1997-07-11",
    title: "📈 @Home IPO",
    description: "@Home goes public, riding internet wave but later fails in dotcom crash",
    type: "ipo",
    connections: ["kp_at_home"],
    lineId: "kp_line",
    importance: 1,
  },
  {
    id: "google_founding",
    date: "1998-09-04",
    title: "🚀 Google Founded",
    description: "Larry Page and Sergey Brin incorporate Google",
    type: "firm_founding",
    connections: ["kp_sequoia_google"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Google",
  },
  {
    id: "kp_sequoia_google",
    date: "1999-06-07",
    title: "💰 KP & Sequoia → Google",
    description: "John Doerr (KP) and Michael Moritz (Sequoia) co-invest $25M in Google",
    type: "investment",
    connections: ["google_founding", "google_ipo", "doerr_joins_kp", "moritz_joins_sequoia"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Google",
  },

  // Sequoia Capital Line - The Disciplined Investors
  {
    id: "sequoia_founding",
    date: "1972-11-01",
    title: "🚀 Sequoia Capital Founded",
    description: "Don Valentine leaves Fairchild to found Sequoia Capital",
    type: "firm_founding",
    connections: [
      "fairchild_founding",
      "valentine_national_semi",
      "sequoia_atari",
      "sequoia_apple",
      "moritz_joins_sequoia",
    ],
    lineId: "sequoia_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Sequoia_Capital",
  },
  {
    id: "valentine_national_semi",
    date: "1967-05-01",
    title: "👔 Valentine → National Semiconductor",
    description: "Don Valentine joins National Semiconductor as marketing director before founding Sequoia",
    type: "person_move",
    connections: ["fairchild_founding", "national_semi_founding", "sequoia_founding"],
    lineId: "sequoia_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Don_Valentine",
  },
  {
    id: "atari_founding",
    date: "1972-06-27",
    title: "🚀 Atari Founded",
    description: "Nolan Bushnell founds Atari, creators of Pong",
    type: "firm_founding",
    connections: ["sequoia_atari"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Atari",
  },
  {
    id: "sequoia_atari",
    date: "1975-01-01",
    title: "💰 Sequoia → Atari",
    description: "Don Valentine invests in Atari, backing video game revolution",
    type: "investment",
    connections: ["sequoia_founding", "atari_founding", "atari_acquisition"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Atari",
  },
  {
    id: "capital_gains_tax_cut",
    date: "1978-11-06",
    title: "⭐ Capital Gains Tax Cut",
    description: "US reduces capital gains tax from 49% to 28%, boosting VC investments",
    type: "milestone",
    connections: ["erisa_prudent_man", "sequoia_apple"],
    lineId: "sequoia_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Revenue_Act_of_1978",
  },
  {
    id: "sequoia_apple",
    date: "1978-01-01",
    title: "💰 Sequoia → Apple",
    description: "Don Valentine invests $150k in Apple Computer for 10% stake",
    type: "investment",
    connections: ["sequoia_founding", "apple_ipo"],
    lineId: "sequoia_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Apple_Inc.",
  },
  {
    id: "atari_acquisition",
    date: "1976-10-01",
    title: "📈 Warner Acquires Atari",
    description: "Warner Communications acquires Atari for $28M",
    type: "acquisition",
    connections: ["sequoia_atari"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Atari",
  },
  {
    id: "apple_ipo",
    date: "1980-12-12",
    title: "📈 Apple IPO",
    description: "Apple IPO creates more millionaires than any company in history to that point",
    type: "ipo",
    connections: ["sequoia_apple"],
    lineId: "sequoia_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Apple_Inc.",
  },
  {
    id: "moritz_joins_sequoia",
    date: "1986-01-01",
    title: "👔 Michael Moritz Joins Sequoia",
    description: "Former Time journalist Michael Moritz joins Sequoia Capital",
    type: "person_move",
    connections: ["sequoia_founding", "sequoia_cisco", "sequoia_yahoo", "kp_sequoia_google"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Michael_Moritz",
  },
  {
    id: "sequoia_cisco",
    date: "1987-12-01",
    title: "💰 Sequoia → Cisco",
    description: "Don Valentine invests $2.5M in Cisco Systems",
    type: "investment",
    connections: ["moritz_joins_sequoia", "cisco_ipo"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Cisco",
  },
  {
    id: "cisco_ipo",
    date: "1990-02-16",
    title: "📈 Cisco IPO",
    description: "Cisco IPO returns 170x to Sequoia, demonstrating networking's potential",
    type: "ipo",
    connections: ["sequoia_cisco"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Cisco",
  },
  {
    id: "sequoia_yahoo",
    date: "1995-04-01",
    title: "💰 Sequoia → Yahoo",
    description: "Michael Moritz leads Sequoia's investment in Yahoo",
    type: "investment",
    connections: ["moritz_joins_sequoia", "yahoo_ipo"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Yahoo!",
  },
  {
    id: "yahoo_ipo",
    date: "1996-04-12",
    title: "📈 Yahoo IPO",
    description: "Yahoo IPO makes Sequoia billions and validates internet search",
    type: "ipo",
    connections: ["sequoia_yahoo"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Yahoo!",
  },
  {
    id: "sequoia_paypal",
    date: "2000-04-01",
    title: "💰 Sequoia → PayPal",
    description: "Sequoia invests in PayPal, backing online payments",
    type: "investment",
    connections: ["sequoia_founding", "paypal_ipo"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/PayPal",
  },
  {
    id: "paypal_ipo",
    date: "2002-02-15",
    title: "📈 PayPal IPO",
    description: "PayPal goes public before acquisition by eBay",
    type: "ipo",
    connections: ["sequoia_paypal", "paypal_ebay_acquisition"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/PayPal",
  },
  {
    id: "paypal_ebay_acquisition",
    date: "2002-10-03",
    title: "📈 eBay Acquires PayPal",
    description: "eBay acquires PayPal for $1.5B, spawning the PayPal Mafia",
    type: "acquisition",
    connections: ["paypal_ipo", "palantir_founding", "spacex_founding", "founders_fund_founding"],
    lineId: "sequoia_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/PayPal",
  },
  {
    id: "sequoia_linkedin",
    date: "2003-06-01",
    title: "💰 Sequoia → LinkedIn",
    description: "Sequoia leads Series A in LinkedIn",
    type: "investment",
    connections: ["sequoia_founding", "linkedin_ipo"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/LinkedIn",
  },
  {
    id: "sequoia_youtube",
    date: "2005-11-01",
    title: "💰 Sequoia → YouTube",
    description: "Sequoia invests $11.5M in YouTube",
    type: "investment",
    connections: ["sequoia_founding", "youtube_acquisition"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/YouTube",
  },
  {
    id: "youtube_acquisition",
    date: "2006-10-09",
    title: "📈 Google Acquires YouTube",
    description: "Google buys YouTube for $1.65B, big return for Sequoia",
    type: "acquisition",
    connections: ["sequoia_youtube"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/YouTube",
  },
  {
    id: "sequoia_whatsapp",
    date: "2011-04-01",
    title: "💰 Sequoia → WhatsApp",
    description: "Jim Goetz leads Sequoia's $8M Series A in WhatsApp",
    type: "investment",
    connections: ["sequoia_founding", "whatsapp_acquisition"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/WhatsApp",
  },
  {
    id: "linkedin_ipo",
    date: "2011-05-19",
    title: "📈 LinkedIn IPO",
    description: "LinkedIn goes public, first major social network IPO",
    type: "ipo",
    connections: ["sequoia_linkedin"],
    lineId: "sequoia_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/LinkedIn",
  },
  {
    id: "whatsapp_acquisition",
    date: "2014-02-19",
    title: "📈 Facebook Acquires WhatsApp",
    description: "Facebook acquires WhatsApp for $19B, Sequoia's $8M becomes $3B",
    type: "acquisition",
    connections: ["sequoia_whatsapp"],
    lineId: "sequoia_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/WhatsApp",
  },

  // Major Market Events
  {
    id: "dotcom_crash",
    date: "2000-03-10",
    title: "⭐ Dot-com Crash Begins",
    description: "NASDAQ peaks at 5,048 then crashes, wiping out hundreds of startups",
    type: "milestone",
    connections: ["google_ipo"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Dot-com_bubble",
  },
  {
    id: "google_ipo",
    date: "2004-08-19",
    title: "📈 Google IPO",
    description: "Google IPO at $85/share returns billions to KP and Sequoia",
    type: "ipo",
    connections: ["kp_sequoia_google", "dotcom_crash"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Google",
  },
  {
    id: "financial_crisis",
    date: "2008-09-15",
    title: "⭐ Financial Crisis",
    description: "Lehman Brothers collapses, credit markets freeze, VC funding plummets",
    type: "milestone",
    connections: ["yc_airbnb", "a16z_founding"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/2007%E2%80%932008_financial_crisis",
  },

  // Accel Partners Line
  {
    id: "accel_founding",
    date: "1983-01-01",
    title: "🚀 Accel Partners Founded",
    description: "Arthur Patterson and Jim Swartz found Accel Partners",
    type: "firm_founding",
    connections: ["accel_facebook"],
    lineId: "accel_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Accel_(venture_capital_firm)",
  },
  {
    id: "accel_facebook",
    date: "2005-05-01",
    title: "💰 Accel → Facebook",
    description: "Jim Breyer leads Accel's $12.7M Series A in Facebook",
    type: "investment",
    connections: ["accel_founding", "facebook_ipo"],
    lineId: "accel_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Facebook",
  },
  {
    id: "accel_etsy",
    date: "2008-01-01",
    title: "💰 Accel → Etsy",
    description: "Accel invests in Etsy, backing artisan marketplace",
    type: "investment",
    connections: ["accel_founding", "etsy_ipo"],
    lineId: "accel_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Etsy",
  },
  {
    id: "accel_slack",
    date: "2014-10-31",
    title: "💰 Accel → Slack",
    description: "Accel leads Series D in Slack",
    type: "investment",
    connections: ["accel_founding", "slack_ipo"],
    lineId: "accel_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Slack_(software)",
  },
  {
    id: "facebook_ipo",
    date: "2012-05-18",
    title: "📈 Facebook IPO",
    description: "Facebook IPO at $38/share returns $15B+ to early investors like Accel",
    type: "ipo",
    connections: ["accel_facebook"],
    lineId: "accel_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Facebook",
  },
  {
    id: "etsy_ipo",
    date: "2015-04-16",
    title: "📈 Etsy IPO",
    description: "Etsy goes public, validating craft e-commerce",
    type: "ipo",
    connections: ["accel_etsy"],
    lineId: "accel_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Etsy",
  },
  {
    id: "slack_ipo",
    date: "2019-06-20",
    title: "📈 Slack IPO",
    description: "Slack direct listing, enterprise software success",
    type: "ipo",
    connections: ["accel_slack"],
    lineId: "accel_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Slack_(software)",
  },

  // Benchmark Capital Line
  {
    id: "benchmark_founding",
    date: "1995-01-01",
    title: "🚀 Benchmark Capital Founded",
    description: "Bob Kagle, Bruce Dunlevie, and team found Benchmark with equal partnership model",
    type: "firm_founding",
    connections: ["benchmark_ebay", "gurley_joins_benchmark", "benchmark_uber"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Benchmark_(venture_capital_firm)",
  },
  {
    id: "benchmark_ebay",
    date: "1997-06-01",
    title: "💰 Benchmark → eBay",
    description: "Benchmark invests $6.7M in eBay for 22% stake",
    type: "investment",
    connections: ["benchmark_founding", "ebay_ipo"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/EBay",
  },
  {
    id: "ebay_ipo",
    date: "1998-09-24",
    title: "📈 eBay IPO",
    description: "eBay IPO returns $5B to Benchmark on $6.7M investment",
    type: "ipo",
    connections: ["benchmark_ebay"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/EBay",
  },
  {
    id: "gurley_joins_benchmark",
    date: "1999-01-01",
    title: "👔 Bill Gurley Joins Benchmark",
    description: "Bill Gurley joins Benchmark as partner",
    type: "person_move",
    connections: ["benchmark_founding", "benchmark_uber"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Bill_Gurley",
  },
  {
    id: "benchmark_twitter",
    date: "2009-01-01",
    title: "💰 Benchmark → Twitter",
    description: "Benchmark invests in Twitter",
    type: "investment",
    connections: ["benchmark_founding", "twitter_ipo"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Twitter",
  },
  {
    id: "benchmark_instagram",
    date: "2011-02-02",
    title: "💰 Benchmark → Instagram",
    description: "Benchmark leads Series A in Instagram",
    type: "investment",
    connections: ["benchmark_founding", "instagram_acquisition"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Instagram",
  },
  {
    id: "benchmark_uber",
    date: "2011-02-01",
    title: "💰 Benchmark → Uber",
    description: "Bill Gurley leads Benchmark's Series A in Uber",
    type: "investment",
    connections: ["benchmark_founding", "gurley_joins_benchmark", "uber_kalanick_ouster", "uber_ipo"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Uber",
  },
  {
    id: "instagram_acquisition",
    date: "2012-04-09",
    title: "📈 Facebook Acquires Instagram",
    description: "Facebook buys Instagram for $1B",
    type: "acquisition",
    connections: ["benchmark_instagram"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Instagram",
  },
  {
    id: "twitter_ipo",
    date: "2013-11-07",
    title: "📈 Twitter IPO",
    description: "Twitter IPO at $26/share, opens at $45.10",
    type: "ipo",
    connections: ["benchmark_twitter"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Twitter",
  },
  {
    id: "uber_kalanick_ouster",
    date: "2017-06-20",
    title: "⭐ Travis Kalanick Ousted from Uber",
    description: "Bill Gurley and investors force out Uber CEO Travis Kalanick amid scandals",
    type: "milestone",
    connections: ["benchmark_uber"],
    lineId: "benchmark_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Travis_Kalanick",
  },
  {
    id: "uber_ipo",
    date: "2019-05-10",
    title: "📈 Uber IPO",
    description: "Uber IPO at $45/share, mixed results but validates ride-sharing",
    type: "ipo",
    connections: ["benchmark_uber"],
    lineId: "benchmark_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Uber",
  },

  // Y Combinator Line - The Accelerator Revolution
  {
    id: "yc_founding",
    date: "2005-03-01",
    title: "🚀 Y Combinator Founded",
    description: "Paul Graham, Jessica Livingston, Trevor Blackwell, Robert Morris found YC",
    type: "firm_founding",
    connections: ["yc_reddit", "yc_dropbox", "yc_airbnb", "yc_stripe"],
    lineId: "yc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Y_Combinator",
  },
  {
    id: "yc_reddit",
    date: "2005-06-01",
    title: "💰 YC → Reddit",
    description: "Y Combinator funds Reddit in first batch",
    type: "investment",
    connections: ["yc_founding"],
    lineId: "yc_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Reddit",
  },
  {
    id: "yc_dropbox",
    date: "2007-06-01",
    title: "💰 YC → Dropbox",
    description: "Y Combinator funds Drew Houston's Dropbox",
    type: "investment",
    connections: ["yc_founding", "dropbox_ipo"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Dropbox",
  },
  {
    id: "yc_airbnb",
    date: "2009-01-01",
    title: "💰 YC → Airbnb",
    description: "Y Combinator accepts Airbnb after initial rejection, during financial crisis",
    type: "investment",
    connections: ["yc_founding", "financial_crisis", "airbnb_ipo"],
    lineId: "yc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Airbnb",
  },
  {
    id: "yc_stripe",
    date: "2010-01-01",
    title: "💰 YC → Stripe",
    description: "Y Combinator funds Stripe in Winter 2010 batch",
    type: "investment",
    connections: ["yc_founding", "stripe_valuation", "founders_stripe"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Stripe_(company)",
  },
  {
    id: "yc_coinbase",
    date: "2012-06-01",
    title: "💰 YC → Coinbase",
    description: "Y Combinator funds Coinbase, crypto exchange",
    type: "investment",
    connections: ["yc_founding", "coinbase_ipo"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Coinbase",
  },
  {
    id: "yc_instacart",
    date: "2012-07-01",
    title: "💰 YC → Instacart",
    description: "Y Combinator funds Instacart, grocery delivery",
    type: "investment",
    connections: ["yc_founding", "instacart_ipo"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Instacart",
  },
  {
    id: "dropbox_ipo",
    date: "2018-03-23",
    title: "📈 Dropbox IPO",
    description: "Dropbox IPO at $21/share validates YC's early bet",
    type: "ipo",
    connections: ["yc_dropbox"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Dropbox",
  },
  {
    id: "stripe_valuation",
    date: "2021-03-14",
    title: "⭐ Stripe Valuation $95B",
    description: "Stripe raises at $95B valuation, YC's biggest success",
    type: "milestone",
    connections: ["yc_stripe"],
    lineId: "yc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Stripe_(company)",
  },
  {
    id: "airbnb_ipo",
    date: "2020-12-10",
    title: "📈 Airbnb IPO",
    description: "Airbnb IPO at $68/share, massive return for YC",
    type: "ipo",
    connections: ["yc_airbnb"],
    lineId: "yc_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Airbnb",
  },
  {
    id: "coinbase_ipo",
    date: "2021-04-14",
    title: "📈 Coinbase IPO",
    description: "Coinbase direct listing, crypto goes mainstream",
    type: "ipo",
    connections: ["yc_coinbase"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Coinbase",
  },
  {
    id: "instacart_ipo",
    date: "2023-09-19",
    title: "📈 Instacart IPO",
    description: "Instacart goes public, grocery delivery validated",
    type: "ipo",
    connections: ["yc_instacart"],
    lineId: "yc_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Instacart",
  },

  // Andreessen Horowitz Line - The New Generation
  {
    id: "a16z_founding",
    date: "2009-07-01",
    title: "🚀 Andreessen Horowitz Founded",
    description: "Marc Andreessen and Ben Horowitz found a16z with $300M fund",
    type: "firm_founding",
    connections: [
      "netscape_founding",
      "netscape_ipo",
      "financial_crisis",
      "a16z_skype",
      "a16z_twitter",
      "a16z_facebook",
    ],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Andreessen_Horowitz",
  },
  {
    id: "a16z_skype",
    date: "2009-09-01",
    title: "💰 a16z → Skype",
    description: "a16z invests in Skype before Microsoft acquisition",
    type: "investment",
    connections: ["a16z_founding", "skype_acquisition"],
    lineId: "a16z_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Skype",
  },
  {
    id: "a16z_twitter",
    date: "2010-09-01",
    title: "💰 a16z → Twitter",
    description: "Andreessen Horowitz leads Twitter's $200M Series C",
    type: "investment",
    connections: ["a16z_founding", "twitter_ipo"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Twitter",
  },
  {
    id: "a16z_facebook",
    date: "2010-12-01",
    title: "💰 a16z → Facebook",
    description: "a16z invests in Facebook's secondary market at $38B valuation",
    type: "investment",
    connections: ["a16z_founding"],
    lineId: "a16z_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Facebook",
  },
  {
    id: "skype_acquisition",
    date: "2011-05-10",
    title: "📈 Microsoft Acquires Skype",
    description: "Microsoft buys Skype for $8.5B",
    type: "acquisition",
    connections: ["a16z_skype"],
    lineId: "a16z_line",
    importance: 1,
    link: "https://en.wikipedia.org/wiki/Skype",
  },
  {
    id: "a16z_github",
    date: "2012-07-09",
    title: "💰 a16z → GitHub",
    description: "a16z leads $100M investment in GitHub",
    type: "investment",
    connections: ["a16z_founding", "github_acquisition"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/GitHub",
  },
  {
    id: "a16z_lyft",
    date: "2013-01-01",
    title: "💰 a16z → Lyft",
    description: "a16z invests in Lyft, Uber competitor",
    type: "investment",
    connections: ["a16z_founding", "lyft_ipo"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Lyft",
  },
  {
    id: "a16z_oculus",
    date: "2013-06-01",
    title: "💰 a16z → Oculus",
    description: "a16z invests in Oculus VR",
    type: "investment",
    connections: ["a16z_founding", "oculus_acquisition"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Oculus_VR",
  },
  {
    id: "oculus_acquisition",
    date: "2014-03-25",
    title: "📈 Facebook Acquires Oculus",
    description: "Facebook buys Oculus for $2B",
    type: "acquisition",
    connections: ["a16z_oculus"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Oculus_VR",
  },
  {
    id: "a16z_coinbase",
    date: "2013-12-01",
    title: "💰 a16z → Coinbase",
    description: "a16z invests in Coinbase Series B",
    type: "investment",
    connections: ["a16z_founding", "coinbase_ipo"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Coinbase",
  },
  {
    id: "github_acquisition",
    date: "2018-06-04",
    title: "📈 Microsoft Acquires GitHub",
    description: "Microsoft buys GitHub for $7.5B",
    type: "acquisition",
    connections: ["a16z_github"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/GitHub",
  },
  {
    id: "lyft_ipo",
    date: "2019-03-29",
    title: "📈 Lyft IPO",
    description: "Lyft IPO at $72/share",
    type: "ipo",
    connections: ["a16z_lyft"],
    lineId: "a16z_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Lyft",
  },

  // Sequoia China Line
  {
    id: "sequoia_china_founding",
    date: "2005-09-01",
    title: "🚀 Sequoia China Founded",
    description: "Neil Shen founds Sequoia China as independent affiliate",
    type: "firm_founding",
    connections: ["sequoia_founding", "sequoia_china_alibaba", "sequoia_china_meituan"],
    lineId: "sequoia_china_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Sequoia_Capital#Sequoia_Capital_China",
  },
  {
    id: "sequoia_china_alibaba",
    date: "2012-01-01",
    title: "💰 Sequoia China → Alibaba (early involvement)",
    description: "Sequoia connections help fund Alibaba, massive China success",
    type: "investment",
    connections: ["sequoia_china_founding", "alibaba_ipo"],
    lineId: "sequoia_china_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Alibaba_Group",
  },
  {
    id: "sequoia_china_meituan",
    date: "2010-03-01",
    title: "💰 Sequoia China → Meituan",
    description: "Sequoia China invests in Meituan, food delivery giant",
    type: "investment",
    connections: ["sequoia_china_founding", "meituan_ipo"],
    lineId: "sequoia_china_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Meituan",
  },
  {
    id: "sequoia_china_jd",
    date: "2011-01-01",
    title: "💰 Sequoia China → JD.com",
    description: "Sequoia China invests in JD.com, e-commerce rival to Alibaba",
    type: "investment",
    connections: ["sequoia_china_founding", "jd_ipo"],
    lineId: "sequoia_china_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/JD.com",
  },
  {
    id: "alibaba_ipo",
    date: "2014-09-19",
    title: "📈 Alibaba IPO",
    description: "Alibaba IPO on NYSE, largest ever at $25B raised",
    type: "ipo",
    connections: ["sequoia_china_alibaba"],
    lineId: "sequoia_china_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Alibaba_Group",
  },
  {
    id: "jd_ipo",
    date: "2014-05-22",
    title: "📈 JD.com IPO",
    description: "JD.com IPO on NASDAQ",
    type: "ipo",
    connections: ["sequoia_china_jd"],
    lineId: "sequoia_china_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/JD.com",
  },
  {
    id: "meituan_ipo",
    date: "2018-09-20",
    title: "📈 Meituan IPO",
    description: "Meituan IPO in Hong Kong, valued at $55B",
    type: "ipo",
    connections: ["sequoia_china_meituan"],
    lineId: "sequoia_china_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Meituan",
  },

  // Cautionary Tales and Failures
  {
    id: "theranos_fraud",
    date: "2015-10-15",
    title: "⭐ Theranos Exposed",
    description: "Wall Street Journal exposes Theranos fraud, cautionary tale of VC hype",
    type: "milestone",
    connections: ["financial_crisis"],
    lineId: "kp_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Theranos",
  },
  {
    id: "wework_failure",
    date: "2019-09-01",
    title: "⭐ WeWork IPO Fails",
    description: "WeWork's attempted IPO collapses amid governance issues and losses",
    type: "milestone",
    connections: ["benchmark_uber"],
    lineId: "benchmark_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/WeWork",
  },

  // Founders Fund Line
  {
    id: "spacex_founding",
    date: "2002-05-06",
    title: "🚀 SpaceX Founded",
    description: "Elon Musk founds SpaceX after PayPal",
    type: "firm_founding",
    connections: ["paypal_ebay_acquisition", "founders_spacex"],
    lineId: "founders_fund_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/SpaceX",
  },
  {
    id: "palantir_founding",
    date: "2003-01-01",
    title: "🚀 Palantir Founded",
    description: "Peter Thiel co-founds Palantir Technologies",
    type: "firm_founding",
    connections: ["paypal_ebay_acquisition", "palantir_ipo"],
    lineId: "founders_fund_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Palantir_Technologies",
  },
  {
    id: "founders_fund_founding",
    date: "2005-07-01",
    title: "🚀 Founders Fund Founded",
    description: "Peter Thiel, Ken Howery, and Luke Nosek found Founders Fund",
    type: "firm_founding",
    connections: ["paypal_ebay_acquisition", "founders_spacex", "founders_stripe"],
    lineId: "founders_fund_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Founders_Fund",
  },
  {
    id: "founders_spacex",
    date: "2008-12-01",
    title: "💰 Founders Fund → SpaceX",
    description: "Founders Fund leads Series D in SpaceX",
    type: "investment",
    connections: ["founders_fund_founding", "spacex_founding"],
    lineId: "founders_fund_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/SpaceX",
  },
  {
    id: "founders_stripe",
    date: "2011-03-28",
    title: "💰 Founders Fund → Stripe",
    description: "Founders Fund invests in Stripe",
    type: "investment",
    connections: ["founders_fund_founding", "yc_stripe"],
    lineId: "founders_fund_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Stripe_(company)",
  },
  {
    id: "palantir_ipo",
    date: "2020-09-30",
    title: "📈 Palantir IPO",
    description: "Palantir direct listing",
    type: "ipo",
    connections: ["palantir_founding"],
    lineId: "founders_fund_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Palantir_Technologies",
  },
  // Venrock additions
  {
    id: "venrock_founding",
    date: "1969-01-01",
    title: "🚀 Venrock Founded",
    description: "Rockefeller family launches Venrock Associates.",
    type: "firm_founding",
    connections: ["venrock_intel", "venrock_apple"],
    lineId: "venrock_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Venrock",
  },
  {
    id: "venrock_intel",
    date: "1969-08-01",
    title: "💰 Venrock → Intel",
    description: "Participates in Intel seed round.",
    type: "investment",
    connections: ["intel_founding"],
    lineId: "venrock_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Intel",
  },
  {
    id: "venrock_apple",
    date: "1978-01-15",
    title: "💰 Venrock → Apple",
    description: "Invests $250k in Apple.",
    type: "investment",
    connections: ["apple_ipo"],
    lineId: "venrock_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/Apple_Inc.",
  },

  // SoftBank / Vision Fund additions
  {
    id: "softbank_founding",
    date: "1981-09-03",
    title: "🚀 SoftBank Founded",
    description: "Masayoshi Son founds SoftBank.",
    type: "firm_founding",
    connections: ["softbank_alibaba"],
    lineId: "softbank_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/SoftBank_Group",
  },
  {
    id: "softbank_yahoo",
    date: "1996-01-01",
    title: "💰 SoftBank → Yahoo",
    description: "Masayoshi Son invests $2M in Yahoo",
    type: "investment",
    connections: ["softbank_founding", "sequoia_yahoo", "yahoo_ipo"],
    lineId: "softbank_line",
    importance: 2,
    link: "https://en.wikipedia.org/wiki/SoftBank_Group",
  },
  {
    id: "softbank_alibaba",
    date: "2000-10-01",
    title: "💰 SoftBank → Alibaba $20M",
    description: "SoftBank invests $20M in Alibaba.",
    type: "investment",
    connections: ["alibaba_ipo"],
    lineId: "softbank_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/Alibaba_Group",
  },
  {
    id: "visionfund_launch",
    date: "2017-10-18",
    title: "⭐ Vision Fund I closes $98B",
    description: "SoftBank Vision Fund I closes at $98B.",
    type: "milestone",
    connections: ["softbank_founding", "visionfund_losses"],
    lineId: "softbank_line",
    importance: 3,
    link: "https://en.wikipedia.org/wiki/SoftBank_Vision_Fund",
  },
  {
    id: "visionfund_losses",
    date: "2022-05-12",
    title: "⭐ Vision Fund posts $27B loss",
    description: "Vision Fund records historic $27B loss.",
    type: "milestone",
    connections: ["visionfund_launch"],
    lineId: "softbank_line",
    importance: 3,
    link: "https://www.ft.com/content/9e0d20ea-745f-4264-83d1-8be2c6e8d6e0",
  },
]

// Assign nodes to their respective lines
subwayLines.forEach((line) => {
  line.nodes = subwayNodes
    .filter((node) => node.lineId === line.id)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
    .map((node) => node.id)
})

const parseDate = (dateString: string): Date => {
  const [year, month, day] = dateString.split("-").map(Number)
  return new Date(year, month - 1, day)
}

const getTimelineRange = (): [Date, Date] => {
  let minDate = new Date()
  let maxDate = new Date(2020, 11, 31) // End when the book ends

  subwayNodes.forEach((node) => {
    const nodeDate = parseDate(node.date)
    if (nodeDate < minDate) minDate = nodeDate
    if (nodeDate > maxDate && nodeDate.getFullYear() <= 2020) maxDate = nodeDate
  })

  minDate.setFullYear(minDate.getFullYear() - 2)
  return [minDate, maxDate]
}
